Mswami678 evaluation db
softsankar/ita-evaluationapp pull request #3
Opened 2020-06-16 22:51 UTC by mswami678

Used try and catch to determine if student exists
changed evaluation actions to utilize try catch
created table in database named skill_set and class named skillset

2020-06-19 01:58 UTC, mswami678 commented
Updated so exception is not raised and added class Skill and return an array

2020-06-20 16:43 UTC, softsankar requested changes
Whenever you select records from table, you don't need to do commit. Commit requires when you add or update records in a table. Commit makes the update/add available to all the other users.

2020-06-20 20:39 UTC, mswami678 reviewed
Oh ok, I have changed the file. So with is for closing the database while commit is only used for updating/adding. Thank you for the feedback.

2020-06-24 15:38 UTC, softsankar approved these changes

2020-06-25 01:23 UTC, Divster116 approved these changes

2020-06-26 03:32 UTC, Mithran573 approved these changes

2020-06-26 03:33 UTC, merged